
### login
POST http://localhost:8000/api/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

### register
POST http://localhost:8000/api/register
content-type: application/json

{
    "name": "test",
    "email": "test2@test.com",
    "password": "password"
}

### get all survey
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0ZXN0QHRlc3QuY29tIiwiZXhwIjoxNjA2NzM0NjkyfQ.iA0Dh7u8Nl14JKhSTFIZrFuZrMP1WgNwX-p1Tq0YhBE

GET http://localhost:8000/api/survey/
content-type: application/json
Authorization: Bearer {{token}}

### get single survey
GET http://localhost:8000/api/survey/5fc08a8b00ee319b006bb825
content-type: application/json

### create a new survey
POST http://localhost:8000/api/survey
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "test",
    "description": "test@test1221.com",
    "userId": "1"
}

### update a survey
PUT http://localhost:8000/api/survey/5fc08a8b00ee319b006bb825
content-type: application/json

{
    "name": "test",
    "description": "aaaa11aaaaa"
}

### delete a survey
DELETE http://localhost:8000/api/survey/5fc08a8b00ee319b006bb825
content-type: application/json
